version: '3.3'
services:

  postgres:
    image: postgres:16.1
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=real-estate-db
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kafka-network

  data-parser:
    restart: always
    container_name: data-parser
    build: ./data-parser
    volumes:
      - ./data-parser:/app
      - ./scraping-source:/app
      - ./protobufs:/app/protobufs
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_SERVER=kafka:29092
    networks:
      - kafka-network

  scraper:
    restart: always
    container_name: scraper
    build: ./scraper
    volumes:
      - ./scraper:/app/scraper
      - ./scraping-source:/app
      - ./protobufs:/app/protobufs
    depends_on:
      - kafka
      - data-parser
      - scraper-status-updater
    environment:
      - KAFKA_SERVER=kafka:29092
    networks:
      - kafka-network
  
  scraper-status-updater:
    restart: always
    container_name: scraper-status-updater
    build: ./scraper-status-updater
    volumes:
      - ./scraper-status-updater:/app
      - ./scraping-source:/app/data
      - ./protobufs:/app/protobufs
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVER=kafka:29092
    networks:
      - kafka-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    volumes:
      - ./zookeeper-data:/var/lib/postgresql/data
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    container_name: kafka
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "unparsed-data:1:1,scraping-progress:1:1"
    depends_on:
      - zookeeper
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge