version: '3.3'
services:
  data-parser:
    container_name: data-parser
    build: ./data-parser
    volumes:
      - ./data-parser:/app
      - ./protobufs:/app/protobufs
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVER=kafka:29092
    networks:
      - kafka-network

  scraper:
    container_name: scraper
    build: ./scraper
    volumes:
      - ./scraper:/app/scraper
      - ./scraping-source:/app
      - ./protobufs:/app/protobufs
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVER=kafka:29092
    networks:
      - kafka-network
  
  scraper-status-updater:
    container_name: scraper-status-updater
    build: ./scraper-status-updater
    volumes:
      - ./scraper-status-updater:/app
      - ./scraping-source:/app/data
      - ./protobufs:/app/protobufs
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVER=kafka:29092
    networks:
      - kafka-network

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=real-estate-db
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    networks:
      - kafka-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    volumes:
      - ./zookeeper-data:/var/lib/postgresql/data
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    container_name: kafka
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "unparsed-data:1:1,scraping-progress:1:1"
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kconnect:
    image: debezium/connect:1.9
    restart: unless-stopped
    container_name: kafka-connect
    ports:
      - 8083:8083
    environment:
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_TOPIC_CREATION_ENABLE: "true"
    volumes:
      - ./config.json:/kafka/connect/config.json
    links:
      - zookeeper
      - postgres
    depends_on:
      - kafka
      - zookeeper
      - postgres
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge