# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scraping-progress-status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scraping-progress-status.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1escraping-progress-status.proto\"5\n\x16ScrapingProgressStatus\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\tb\x06proto3'
)




_SCRAPINGPROGRESSSTATUS = _descriptor.Descriptor(
  name='ScrapingProgressStatus',
  full_name='ScrapingProgressStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='ScrapingProgressStatus.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='ScrapingProgressStatus.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['ScrapingProgressStatus'] = _SCRAPINGPROGRESSSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScrapingProgressStatus = _reflection.GeneratedProtocolMessageType('ScrapingProgressStatus', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPINGPROGRESSSTATUS,
  '__module__' : 'scraping_progress_status_pb2'
  # @@protoc_insertion_point(class_scope:ScrapingProgressStatus)
  })
_sym_db.RegisterMessage(ScrapingProgressStatus)


# @@protoc_insertion_point(module_scope)
