FROM python:3.10.12

WORKDIR /scraper

COPY . /scraper

RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install-deps
RUN playwright install

RUN chmod +x verify_on_startup.sh
RUN chmod +x start_process.sh

