# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unparsed-html-message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='unparsed-html-message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bunparsed-html-message.proto\"9\n\x13UnparsedHtmlMessage\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x15\n\runparsed_html\x18\x02 \x01(\tb\x06proto3'
)




_UNPARSEDHTMLMESSAGE = _descriptor.Descriptor(
  name='UnparsedHtmlMessage',
  full_name='UnparsedHtmlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='UnparsedHtmlMessage.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unparsed_html', full_name='UnparsedHtmlMessage.unparsed_html', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['UnparsedHtmlMessage'] = _UNPARSEDHTMLMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnparsedHtmlMessage = _reflection.GeneratedProtocolMessageType('UnparsedHtmlMessage', (_message.Message,), {
  'DESCRIPTOR' : _UNPARSEDHTMLMESSAGE,
  '__module__' : 'unparsed_html_message_pb2'
  # @@protoc_insertion_point(class_scope:UnparsedHtmlMessage)
  })
_sym_db.RegisterMessage(UnparsedHtmlMessage)


# @@protoc_insertion_point(module_scope)
